### ISSUE TITLE
Type "o" in forecast script (v5.17)

### ISSUE THREAD

**Issue by Stevec4** [ktrue/NWS-forecast#1]
Ken I had an error recently and think I found a type o in the version 5.17 file

line 588 
`if (jason_last_error() !== JSON_ERROR_NONE) {`

I believe it should be.
`if (json_last_error() !== JSON_ERROR_NONE) {`

steve

**Comment by ktrue** [comment]
Yes, It's been there for quite a while, and ignored completely by PHP 7 and below.  Only PHP 8 seemed to parse and complain about it.  Thanks for the discovery.  I've fixed it in the distribution, but kept the version as 5.17.
